language: java
install: true
os: linux
jdk:
- openjdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
- "./gradlew clean test"
env:
  global:
  - PACT_BROKER_BASE_URL=https://dius.pactflow.io
  # PACT_BROKER_TOKEN
  - secure: "IXxQXupweQDSgEiXIwmgefCeoj0cqH9lyRQKNURWm/P7qg9DSFcUpzk+2pvgLlQx0iwxVd9cuv6PxW1kguH0KeLVv1cp3K0Nt1j15XpKlZwMz99J+SSDkeGcdzicxO3YadH71WhA7GeP/1008Acp2fda1A5FvXM4DhvFflhwrE26sKNMc89gPT7s1DBPwcRYbm/DsFRkPkUq7bNVGr3FSYKakyaeVtgOtPNj3SdRPnhRpUl4IJgTuwu5Emn4heHQjNc5fhRBZSv1HM7tLR7mMbSLFqe5/fNcxih4J836tZFXXJdWbigdJt97sgS5Z1OFopjki9imHr0SaUbvoXzWuQuglnJ9nANH2zVPkH/QcU9Emdo+eWesJhNfIT1dJQCC+EnXI4Wj0PlEdmzDtVvO93JQ36nZvdmJKmaeDWrOmic+hCt287972jKpDehGX6p64OsATk743vaqbA//lAWXFmbAsCztIsximDvBnoCTVOzMLh4iU/u+F5vrbLxcIwlia7Ij/yl6lB+bP/w2BvRU6ghcR+BJBeHRuP13F0XPao4CNut23nQpEasJYQ6xOBjZsvUgZOOYcQDhd3TSnuhex7ry6BbAlcpkBqrM6uSSkNpBf2SlOEOeLUIB8FiEhG3GMbBUWp3aYRMIQtHuY6LOWrc1OFVeTsUVc0fYU1BD8W8="

